// Rich, realistic Trumbull seed data for Atlas.
// Pure data — no backend calls. Shapes mirror lib/types.ts (and the SQL schema)
// so this module can be replaced by Supabase queries later.

import type {
  ActivityEntry,
  AuditBucket,
  AuditItem,
  Comment,
  Label,
  Person,
  Project,
  Status,
  Subtask,
  Task,
} from "./types";

// ── Reference "today" so the demo is stable regardless of wall-clock time.
export const TODAY = "2026-06-27";

// ── People ───────────────────────────────────────────────────────────────────
// Real Trumbull team members from Users.xlsx.
// Email format: firstinitiallastname@trumbull.com
// The first 6 entries also carry the old demo IDs ("u_jl" etc.) so existing
// task references (ownerId, assigneeIds, comments, activity) keep working.
export const PEOPLE: Person[] = [
  // ── Original 6 (mapped from demo personas to real people) ────────────────
  { id: "u_jl", initials: "MN", fullName: "Michael Nichols", email: "mnichols@trumbull.com", role: "admin", hue: 162 },
  { id: "u_dt", initials: "SS", fullName: "Stephanie Schermer", email: "sschermer@trumbull.com", role: "member", hue: 36 },
  { id: "u_sk", initials: "SA", fullName: "Shawn Allen", email: "sallen@trumbull.com", role: "member", hue: 54 },
  { id: "u_mr", initials: "SW", fullName: "Shawn Walker", email: "swalker@trumbull.com", role: "member", hue: 72 },
  { id: "u_ap", initials: "CS", fullName: "Colin Snelson", email: "csnelson@trumbull.com", role: "member", hue: 90 },
  { id: "u_cb", initials: "CT", fullName: "Colin Temnick", email: "ctemnick@trumbull.com", role: "member", hue: 108 },
  // ── Remaining Trumbull team ──────────────────────────────────────────────
  { id: "u_jv", initials: "JV", fullName: "Joe Vingle", email: "jvingle@trumbull.com", role: "member", hue: 0 },
  { id: "u_aw", initials: "AW", fullName: "Alison Walton", email: "awalton@trumbull.com", role: "member", hue: 126 },
  { id: "u_eh", initials: "EH", fullName: "Emily Huston", email: "ehuston@trumbull.com", role: "member", hue: 144 },
  { id: "u_cn", initials: "CN", fullName: "Colette Nichols", email: "cnichols@trumbull.com", role: "member", hue: 180 },
  { id: "u_as", initials: "AS", fullName: "Abhi Shah", email: "ashah@trumbull.com", role: "member", hue: 198 },
  { id: "u_sm", initials: "SM", fullName: "Sabin Maharjan", email: "smaharjan@trumbull.com", role: "member", hue: 216 },
  { id: "u_yt", initials: "YT", fullName: "Yi-Ting Tsan", email: "ytsan@trumbull.com", role: "member", hue: 234 },
  { id: "u_dm", initials: "DM", fullName: "Derek Menzies", email: "dmenzies@trumbull.com", role: "member", hue: 252 },
  { id: "u_av", initials: "AV", fullName: "Alex Velicer", email: "avelicer@trumbull.com", role: "member", hue: 270 },
  { id: "u_ml", initials: "ML", fullName: "Michelle Lawson", email: "mlawson@trumbull.com", role: "member", hue: 288 },
  { id: "u_mp", initials: "MP", fullName: "Michelle Purcell", email: "mpurcell@trumbull.com", role: "member", hue: 306 },
  { id: "u_rs", initials: "RS", fullName: "Rita Stringham", email: "rstringham@trumbull.com", role: "member", hue: 324 },
  { id: "u_jla", initials: "JL", fullName: "Jennifer Laws", email: "jlaws@trumbull.com", role: "member", hue: 342 },
  { id: "u_at", initials: "AT", fullName: "Andrew Toms", email: "atoms@trumbull.com", role: "member", hue: 18 },
];

// Default logged-in user (Michael Nichols) — will be replaced by Supabase auth
export const ME = "u_jl";

export function person(id: string | null | undefined): Person | undefined {
  return PEOPLE.find((p) => p.id === id);
}

// ── Statuses (one workflow shared by the standard projects) ───────────────────
export const STATUSES: Status[] = [
  { id: "s_backlog", key: "backlog", name: "Backlog", color: "#8c90a0", position: 0, isDone: false },
  { id: "s_todo", key: "todo", name: "To do", color: "#afc6ff", position: 1, isDone: false },
  { id: "s_doing", key: "doing", name: "In progress", color: "#548dff", position: 2, isDone: false },
  { id: "s_review", key: "review", name: "Review", color: "#c0c1ff", position: 3, isDone: false },
  { id: "s_done", key: "done", name: "Verified", color: "#4edea3", position: 4, isDone: true },
];

export const STATUS_BY_KEY: Record<string, Status> = Object.fromEntries(
  STATUSES.map((s) => [s.key, s]),
);

// ── Projects ──────────────────────────────────────────────────────────────────
export const PROJECTS: Project[] = [
  {
    id: "p_silicone",
    name: "Remove discontinued silicone references",
    description:
      "Sweep every live listing and asset for references to the discontinued silicone caulk bundle and replace with the approved adhesive language.",
    kind: "audit",
    objective: "Done = 412/412 listings verified clean across Amazon, Walmart & Wayfair.",
    color: "#548dff",
    health: "at_risk",
    archived: false,
  },
  {
    id: "p_pricing",
    name: "Q3 pricing realignment — Amazon",
    description:
      "Reprice the bath surround and shower-door catalog on Amazon to hit Q3 margin targets without tripping suppression.",
    kind: "standard",
    objective: "Done = all 84 ASINs repriced, buy-box retained, margin ≥ 31%.",
    color: "#4edea3",
    health: "on_track",
    archived: false,
  },
  {
    id: "p_photo",
    name: "Shower wall photography refresh",
    description:
      "New lifestyle + spec photography for the 2026 shower wall line, propagated to all three marketplaces.",
    kind: "standard",
    objective: "Done = hero + 6 gallery images live for all 18 SKUs.",
    color: "#c0c1ff",
    health: "blocked",
    archived: false,
  },
  {
    id: "p_walmart",
    name: "Walmart new bath line launch",
    description:
      "Stand up the new Sterling bath collection on Walmart Marketplace: listings, content, compliance and inventory feeds.",
    kind: "standard",
    objective: "Done = 22 SKUs live, content score ≥ 90, inventory syncing.",
    color: "#f59e0b",
    health: "on_track",
    archived: false,
  },
  {
    id: "p_compliance",
    name: "Marketplace compliance sweep",
    description:
      "Quarterly compliance pass: Prop 65, CARB, packaging claims and restricted-keyword review across the catalog.",
    kind: "standard",
    objective: "Done = 0 open compliance flags across all marketplaces.",
    color: "#f43f5e",
    health: "at_risk",
    archived: false,
  },
];

export function project(id: string): Project | undefined {
  return PROJECTS.find((p) => p.id === id);
}

// ── Labels ────────────────────────────────────────────────────────────────────
const L = {
  content: { id: "l_content", name: "Content", color: "#548dff" },
  images: { id: "l_images", name: "Imagery", color: "#c0c1ff" },
  pricing: { id: "l_pricing", name: "Pricing", color: "#4edea3" },
  compliance: { id: "l_compliance", name: "Compliance", color: "#f43f5e" },
  vendor: { id: "l_vendor", name: "Vendor", color: "#f59e0b" },
  seo: { id: "l_seo", name: "SEO", color: "#8083ff" },
} satisfies Record<string, Label>;

// ── Small builders to keep the task list readable ────────────────────────────
let _id = 0;
const nid = (prefix: string) => `${prefix}_${(++_id).toString(36)}`;

function check(label: string, done: boolean): { id: string; label: string; done: boolean } {
  return { id: nid("ck"), label, done };
}
function sub(title: string, done: boolean, ownerId?: string): Subtask {
  return { id: nid("st"), title, done, ownerId };
}
function comment(authorId: string, body: string, createdAt: string): Comment {
  return { id: nid("cm"), authorId, body, createdAt };
}
function act(kind: ActivityEntry["kind"], actorId: string, text: string, createdAt: string): ActivityEntry {
  return { id: nid("ac"), kind, actorId, text, createdAt };
}

// ── Tasks ─────────────────────────────────────────────────────────────────────
// A generous spread across projects, statuses, priorities and marketplaces.
export const TASKS: Task[] = [
  // ===== Remove discontinued silicone references (audit project work items) =====
  {
    id: "t_sil_1",
    projectId: "p_silicone",
    statusKey: "doing",
    title: "Audit Amazon A+ content for silicone mentions",
    description:
      "Walk every A+ module on the 96 Amazon shower-wall ASINs and strip references to the discontinued silicone caulk bundle. Replace with the approved 'pre-applied adhesive' language from the content kit.",
    priority: 1,
    position: 0,
    dueDate: "2026-06-29",
    marketplace: "Amazon",
    sku: "SW-AMZ-A+",
    ownerId: "u_jl",
    assigneeIds: ["u_jl", "u_ap"],
    labels: [L.content, L.compliance],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [
      check("Pull A+ module export from Seller Central", true),
      check("Flag modules containing 'silicone'", true),
      check("Swap to approved adhesive copy", false),
      check("Re-upload & confirm render", false),
    ],
    subtasks: [
      sub("Surround ASINs (40)", true, "u_jl"),
      sub("Tub/shower ASINs (36)", false, "u_ap"),
      sub("Accessory ASINs (20)", false, "u_ap"),
    ],
    comments: [
      comment("u_ap", "Found 11 modules still referencing the old bundle in the surround set.", "2026-06-26T15:10:00Z"),
      comment("u_jl", "Nice — those are the priority. I'll take the first 40, you take the rest.", "2026-06-26T15:22:00Z"),
    ],
    activity: [
      act("created", "u_jl", "created this task", "2026-06-22T13:00:00Z"),
      act("status", "u_jl", "moved to In progress", "2026-06-24T09:30:00Z"),
      act("checklist", "u_jl", "checked “Pull A+ module export from Seller Central”", "2026-06-24T10:02:00Z"),
    ],
    estimateMinutes: 480,
    createdAt: "2026-06-22T13:00:00Z",
  },
  {
    id: "t_sil_2",
    projectId: "p_silicone",
    statusKey: "doing",
    title: "Walmart spec sheets — replace silicone line items",
    description:
      "The downloadable spec PDFs on Walmart still list the silicone caulk as included. Update the source InDesign files and re-attach.",
    priority: 2,
    position: 1,
    dueDate: "2026-07-01",
    marketplace: "Walmart",
    sku: "SW-WMT-SPEC",
    ownerId: "u_dt",
    assigneeIds: ["u_dt"],
    labels: [L.content],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [
      check("Locate source spec files", true),
      check("Edit included-items table", false),
      check("Re-export PDFs", false),
      check("Attach to Walmart listings", false),
    ],
    subtasks: [],
    comments: [
      comment("u_dt", "Design has the source files in the 2026 spec folder, pulling now.", "2026-06-25T18:00:00Z"),
    ],
    activity: [
      act("created", "u_jl", "created this task", "2026-06-22T13:05:00Z"),
      act("assigned", "u_jl", "assigned Dana Torres", "2026-06-22T13:06:00Z"),
      act("status", "u_dt", "moved to In progress", "2026-06-25T17:40:00Z"),
    ],
    estimateMinutes: 240,
    createdAt: "2026-06-22T13:05:00Z",
  },
  {
    id: "t_sil_3",
    projectId: "p_silicone",
    statusKey: "blocked",
    title: "Wayfair packaging photos show old caulk tube",
    description:
      "Several Wayfair gallery images include the discontinued silicone tube in the packaging shot. These need to be re-shot or retouched out before the listings can be cleared.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-03",
    marketplace: "Wayfair",
    sku: "SW-WAY-IMG",
    ownerId: "u_sk",
    assigneeIds: ["u_sk", "u_mr"],
    labels: [L.images, L.vendor],
    isBlocked: true,
    blockedReason: "Studio re-shoot slot not confirmed — waiting on vendor calendar.",
    blockedSince: "2026-06-24T16:00:00Z",
    checklist: [
      check("Identify affected gallery images", true),
      check("Decide retouch vs re-shoot", true),
      check("Book studio / retoucher", false),
    ],
    subtasks: [
      sub("List affected SKUs", true, "u_sk"),
      sub("Get retouch quote", false, "u_mr"),
    ],
    comments: [
      comment("u_sk", "Retoucher can do 6 of the 9, the other 3 need a real re-shoot.", "2026-06-24T14:30:00Z"),
      comment("u_mr", "Studio is booked through the 2nd. Chasing the vendor for the next open slot.", "2026-06-24T16:05:00Z"),
    ],
    activity: [
      act("created", "u_sk", "created this task", "2026-06-23T11:00:00Z"),
      act("blocked", "u_mr", "marked blocked — waiting on vendor calendar", "2026-06-24T16:00:00Z"),
    ],
    estimateMinutes: 600,
    createdAt: "2026-06-23T11:00:00Z",
  },
  {
    id: "t_sil_4",
    projectId: "p_silicone",
    statusKey: "review",
    title: "Cross-channel FAQ + install guide sweep",
    description:
      "Help-content, FAQ entries and downloadable install guides reference the silicone step. Update copy to the new adhesive workflow and route for compliance sign-off.",
    priority: 3,
    position: 0,
    dueDate: "2026-06-30",
    marketplace: null,
    sku: null,
    ownerId: "u_mr",
    assigneeIds: ["u_mr"],
    labels: [L.content, L.compliance],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [
      check("Update FAQ entries", true),
      check("Update install guide PDF", true),
      check("Compliance review", false),
    ],
    subtasks: [],
    comments: [
      comment("u_mr", "Draft is in review with compliance, expecting sign-off tomorrow.", "2026-06-26T12:00:00Z"),
    ],
    activity: [
      act("created", "u_jl", "created this task", "2026-06-22T13:10:00Z"),
      act("status", "u_mr", "moved to Review", "2026-06-26T11:55:00Z"),
    ],
    estimateMinutes: 180,
    createdAt: "2026-06-22T13:10:00Z",
  },
  {
    id: "t_sil_5",
    projectId: "p_silicone",
    statusKey: "done",
    title: "Amazon bullet points — silicone language removed",
    description: "Bullet points across the surround line scrubbed and re-published.",
    priority: 2,
    position: 0,
    dueDate: "2026-06-20",
    marketplace: "Amazon",
    sku: "SW-AMZ-BULLET",
    ownerId: "u_jl",
    assigneeIds: ["u_jl"],
    labels: [L.content, L.seo],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Update bullets", true), check("Re-publish", true), check("Verify live", true)],
    subtasks: [],
    comments: [],
    activity: [
      act("created", "u_jl", "created this task", "2026-06-15T09:00:00Z"),
      act("status", "u_jl", "moved to Verified", "2026-06-20T16:20:00Z"),
    ],
    estimateMinutes: 120,
    createdAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "t_sil_6",
    projectId: "p_silicone",
    statusKey: "backlog",
    title: "Sweep marketplace ad copy & sponsored creatives",
    description:
      "Sponsored Brand headlines and storefront tiles may still mention the bundle. Audit after the listing sweep completes.",
    priority: 4,
    position: 0,
    dueDate: "2026-07-10",
    marketplace: null,
    sku: null,
    ownerId: "u_ap",
    assigneeIds: ["u_ap"],
    labels: [L.content],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_jl", "created this task", "2026-06-22T13:20:00Z")],
    estimateMinutes: 90,
    createdAt: "2026-06-22T13:20:00Z",
  },

  // ===== Q3 pricing realignment — Amazon =====
  {
    id: "t_pr_1",
    projectId: "p_pricing",
    statusKey: "doing",
    title: "Model margin floors for surround SKUs",
    description:
      "Build the price/margin model for the 40 surround ASINs incorporating the new freight surcharge and 31% target margin.",
    priority: 1,
    position: 0,
    dueDate: "2026-06-28",
    marketplace: "Amazon",
    sku: "SUR-*",
    ownerId: "u_cb",
    assigneeIds: ["u_cb", "u_jl"],
    labels: [L.pricing],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [
      check("Pull current cost basis", true),
      check("Layer in freight surcharge", true),
      check("Compute floors at 31%", false),
      check("Sanity-check vs buy-box", false),
    ],
    subtasks: [sub("Validate against last 30d buy-box win rate", false, "u_jl")],
    comments: [
      comment("u_cb", "Freight surcharge moves 7 SKUs below their current price. Flagging for review.", "2026-06-26T17:30:00Z"),
    ],
    activity: [
      act("created", "u_cb", "created this task", "2026-06-23T10:00:00Z"),
      act("status", "u_cb", "moved to In progress", "2026-06-24T08:45:00Z"),
    ],
    estimateMinutes: 300,
    createdAt: "2026-06-23T10:00:00Z",
  },
  {
    id: "t_pr_2",
    projectId: "p_pricing",
    statusKey: "todo",
    title: "Stage repricing batch in Seller Central",
    description: "Load the approved price changes as a staged batch; do not publish until sign-off.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-01",
    marketplace: "Amazon",
    sku: "SUR-*",
    ownerId: "u_cb",
    assigneeIds: ["u_cb"],
    labels: [L.pricing],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Build upload sheet", false), check("Dry-run validation", false)],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_cb", "created this task", "2026-06-23T10:05:00Z")],
    estimateMinutes: 120,
    createdAt: "2026-06-23T10:05:00Z",
  },
  {
    id: "t_pr_3",
    projectId: "p_pricing",
    statusKey: "review",
    title: "Finance sign-off on margin targets",
    description: "Route the margin model to finance for approval before any prices go live.",
    priority: 2,
    position: 0,
    dueDate: "2026-06-30",
    marketplace: "Amazon",
    sku: null,
    ownerId: "u_jl",
    assigneeIds: ["u_jl"],
    labels: [L.pricing],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Package model summary", true), check("Send to finance", true), check("Incorporate feedback", false)],
    subtasks: [],
    comments: [comment("u_jl", "Finance wants to see the 7 below-cost SKUs broken out separately.", "2026-06-26T19:00:00Z")],
    activity: [
      act("created", "u_jl", "created this task", "2026-06-23T10:10:00Z"),
      act("status", "u_jl", "moved to Review", "2026-06-26T18:50:00Z"),
    ],
    estimateMinutes: 60,
    createdAt: "2026-06-23T10:10:00Z",
  },
  {
    id: "t_pr_4",
    projectId: "p_pricing",
    statusKey: "done",
    title: "Competitive price scrape — top 25 ASINs",
    description: "Captured competitor pricing to anchor the realignment.",
    priority: 3,
    position: 0,
    dueDate: "2026-06-18",
    marketplace: "Amazon",
    sku: null,
    ownerId: "u_cb",
    assigneeIds: ["u_cb"],
    labels: [L.pricing, L.seo],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Scrape", true), check("Normalize", true)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_cb", "moved to Verified", "2026-06-18T15:00:00Z")],
    estimateMinutes: 90,
    createdAt: "2026-06-12T09:00:00Z",
  },

  // ===== Shower wall photography refresh =====
  {
    id: "t_ph_1",
    projectId: "p_photo",
    statusKey: "blocked",
    title: "Re-shoot hero images — 2026 shower wall line",
    description:
      "Studio session for the 18-SKU hero set. Lighting and staging per the 2026 brand guide.",
    priority: 1,
    position: 0,
    dueDate: "2026-07-02",
    marketplace: null,
    sku: "SW-2026",
    ownerId: "u_sk",
    assigneeIds: ["u_sk"],
    labels: [L.images, L.vendor],
    isBlocked: true,
    blockedReason: "Photographer rescheduled — new date pending studio availability.",
    blockedSince: "2026-06-25T13:00:00Z",
    checklist: [check("Confirm shot list", true), check("Stage samples", true), check("Book photographer", false)],
    subtasks: [sub("Pull product samples from warehouse", true, "u_mr")],
    comments: [
      comment("u_sk", "Photographer pushed us a week. Trying to hold the staging so we don't re-prep.", "2026-06-25T13:05:00Z"),
    ],
    activity: [
      act("created", "u_sk", "created this task", "2026-06-19T10:00:00Z"),
      act("blocked", "u_sk", "marked blocked — photographer rescheduled", "2026-06-25T13:00:00Z"),
    ],
    estimateMinutes: 720,
    createdAt: "2026-06-19T10:00:00Z",
  },
  {
    id: "t_ph_2",
    projectId: "p_photo",
    statusKey: "todo",
    title: "Retouch + color-correct gallery set",
    description: "Post-production pass on the gallery images once the shoot lands.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-08",
    marketplace: null,
    sku: "SW-2026",
    ownerId: "u_mr",
    assigneeIds: ["u_mr"],
    labels: [L.images],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_sk", "created this task", "2026-06-19T10:05:00Z")],
    estimateMinutes: 300,
    createdAt: "2026-06-19T10:05:00Z",
  },
  {
    id: "t_ph_3",
    projectId: "p_photo",
    statusKey: "backlog",
    title: "Propagate finals to all three marketplaces",
    description: "Push approved hero + 6 gallery images to Amazon, Walmart and Wayfair for all 18 SKUs.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-14",
    marketplace: null,
    sku: "SW-2026",
    ownerId: "u_ap",
    assigneeIds: ["u_ap", "u_dt"],
    labels: [L.images, L.content],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_sk", "created this task", "2026-06-19T10:10:00Z")],
    estimateMinutes: 240,
    createdAt: "2026-06-19T10:10:00Z",
  },
  {
    id: "t_ph_4",
    projectId: "p_photo",
    statusKey: "done",
    title: "Approve 2026 staging & shot list",
    description: "Brand-approved staging guide and per-SKU shot list.",
    priority: 3,
    position: 0,
    dueDate: "2026-06-16",
    marketplace: null,
    sku: null,
    ownerId: "u_sk",
    assigneeIds: ["u_sk", "u_jl"],
    labels: [L.images],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Draft shot list", true), check("Brand review", true)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_jl", "moved to Verified", "2026-06-16T14:00:00Z")],
    estimateMinutes: 120,
    createdAt: "2026-06-10T09:00:00Z",
  },

  // ===== Walmart new bath line launch =====
  {
    id: "t_wm_1",
    projectId: "p_walmart",
    statusKey: "doing",
    title: "Build 22 listings from content kit",
    description:
      "Create the new Sterling bath collection listings on Walmart Marketplace using the approved content kit. Target content score ≥ 90.",
    priority: 1,
    position: 0,
    dueDate: "2026-06-30",
    marketplace: "Walmart",
    sku: "STERLING-BATH",
    ownerId: "u_dt",
    assigneeIds: ["u_dt", "u_ap"],
    labels: [L.content, L.seo],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [
      check("Map content kit → Walmart attributes", true),
      check("Draft 22 titles + bullets", true),
      check("Load via Item Setup", false),
      check("QA content score", false),
    ],
    subtasks: [
      sub("Surrounds (8)", true, "u_dt"),
      sub("Tubs (6)", false, "u_dt"),
      sub("Doors + accessories (8)", false, "u_ap"),
    ],
    comments: [
      comment("u_ap", "Content score is landing around 87 — need richer attributes on the doors.", "2026-06-26T20:00:00Z"),
    ],
    activity: [
      act("created", "u_dt", "created this task", "2026-06-20T09:00:00Z"),
      act("status", "u_dt", "moved to In progress", "2026-06-22T10:00:00Z"),
    ],
    estimateMinutes: 600,
    createdAt: "2026-06-20T09:00:00Z",
  },
  {
    id: "t_wm_2",
    projectId: "p_walmart",
    statusKey: "todo",
    title: "Wire inventory + price feeds",
    description: "Connect the new SKUs to the inventory and pricing feeds and confirm sync.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-03",
    marketplace: "Walmart",
    sku: "STERLING-BATH",
    ownerId: "u_cb",
    assigneeIds: ["u_cb"],
    labels: [L.pricing],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Map SKUs to feed", false), check("Test sync", false)],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_dt", "created this task", "2026-06-20T09:05:00Z")],
    estimateMinutes: 180,
    createdAt: "2026-06-20T09:05:00Z",
  },
  {
    id: "t_wm_3",
    projectId: "p_walmart",
    statusKey: "review",
    title: "Compliance review of new bath claims",
    description: "Verify packaging claims and restricted keywords for the new collection before go-live.",
    priority: 2,
    position: 0,
    dueDate: "2026-06-30",
    marketplace: "Walmart",
    sku: null,
    ownerId: "u_mr",
    assigneeIds: ["u_mr"],
    labels: [L.compliance],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Claims review", true), check("Restricted-keyword scan", false)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_mr", "moved to Review", "2026-06-26T16:00:00Z")],
    estimateMinutes: 120,
    createdAt: "2026-06-20T09:10:00Z",
  },
  {
    id: "t_wm_4",
    projectId: "p_walmart",
    statusKey: "done",
    title: "Reserve GTINs / item IDs",
    description: "GTINs reserved and mapped for the 22 launch SKUs.",
    priority: 3,
    position: 0,
    dueDate: "2026-06-15",
    marketplace: "Walmart",
    sku: null,
    ownerId: "u_dt",
    assigneeIds: ["u_dt"],
    labels: [],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Reserve GTINs", true)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_dt", "moved to Verified", "2026-06-15T11:00:00Z")],
    estimateMinutes: 60,
    createdAt: "2026-06-11T09:00:00Z",
  },

  // ===== Marketplace compliance sweep =====
  {
    id: "t_cm_1",
    projectId: "p_compliance",
    statusKey: "blocked",
    title: "Resolve Amazon Prop 65 warning flags",
    description:
      "Several surround ASINs are flagged for missing Prop 65 warnings. Need legal-approved warning text before updating listings.",
    priority: 1,
    position: 0,
    dueDate: "2026-06-29",
    marketplace: "Amazon",
    sku: null,
    ownerId: "u_mr",
    assigneeIds: ["u_mr", "u_jl"],
    labels: [L.compliance],
    isBlocked: true,
    blockedReason: "Awaiting legal-approved Prop 65 warning language.",
    blockedSince: "2026-06-23T15:00:00Z",
    checklist: [check("List flagged ASINs", true), check("Request legal language", true), check("Apply to listings", false)],
    subtasks: [],
    comments: [
      comment("u_mr", "Legal says draft language by EOW. 9 ASINs affected.", "2026-06-23T15:10:00Z"),
    ],
    activity: [
      act("created", "u_mr", "created this task", "2026-06-21T09:00:00Z"),
      act("blocked", "u_mr", "marked blocked — awaiting legal language", "2026-06-23T15:00:00Z"),
    ],
    estimateMinutes: 240,
    createdAt: "2026-06-21T09:00:00Z",
  },
  {
    id: "t_cm_2",
    projectId: "p_compliance",
    statusKey: "doing",
    title: "CARB compliance docs for adhesive components",
    description: "Collect and file CARB compliance documentation for the new adhesive used across the bath line.",
    priority: 2,
    position: 0,
    dueDate: "2026-07-02",
    marketplace: null,
    sku: null,
    ownerId: "u_jl",
    assigneeIds: ["u_jl"],
    labels: [L.compliance, L.vendor],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Request docs from supplier", true), check("File in compliance vault", false)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_jl", "moved to In progress", "2026-06-24T10:00:00Z")],
    estimateMinutes: 120,
    createdAt: "2026-06-21T09:05:00Z",
  },
  {
    id: "t_cm_3",
    projectId: "p_compliance",
    statusKey: "todo",
    title: "Restricted-keyword scan across catalog",
    description: "Run the restricted-keyword scan on all live listings and triage hits.",
    priority: 3,
    position: 0,
    dueDate: "2026-07-05",
    marketplace: null,
    sku: null,
    ownerId: "u_ap",
    assigneeIds: ["u_ap"],
    labels: [L.compliance, L.seo],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [],
    subtasks: [],
    comments: [],
    activity: [act("created", "u_jl", "created this task", "2026-06-21T09:10:00Z")],
    estimateMinutes: 180,
    createdAt: "2026-06-21T09:10:00Z",
  },
  {
    id: "t_cm_4",
    projectId: "p_compliance",
    statusKey: "done",
    title: "Packaging claims audit — Wayfair",
    description: "Wayfair packaging claims reviewed and cleared.",
    priority: 3,
    position: 0,
    dueDate: "2026-06-17",
    marketplace: "Wayfair",
    sku: null,
    ownerId: "u_mr",
    assigneeIds: ["u_mr"],
    labels: [L.compliance],
    isBlocked: false,
    blockedReason: null,
    blockedSince: null,
    checklist: [check("Review claims", true), check("Clear", true)],
    subtasks: [],
    comments: [],
    activity: [act("status", "u_mr", "moved to Verified", "2026-06-17T13:00:00Z")],
    estimateMinutes: 120,
    createdAt: "2026-06-13T09:00:00Z",
  },
];

// ── Audit ledger (the "silicone" project's defined item universe) ─────────────
// Realistic sample rows for the table; full counts live in AUDIT_BUCKETS so the
// coverage meter reflects the true 412-item universe.
export const AUDIT_ITEMS: AuditItem[] = [
  { id: "a_1", projectId: "p_silicone", externalRef: "B07SW-SUR-3248", title: "60×32 Alcove Surround — White", marketplace: "Amazon", status: "verified", ownerId: "u_jl", notes: "Bullets + A+ clean", verifiedAt: "2026-06-20T16:00:00Z" },
  { id: "a_2", projectId: "p_silicone", externalRef: "B07SW-SUR-3249", title: "60×32 Alcove Surround — Biscuit", marketplace: "Amazon", status: "verified", ownerId: "u_jl", notes: null, verifiedAt: "2026-06-20T16:05:00Z" },
  { id: "a_3", projectId: "p_silicone", externalRef: "B08SW-TUB-1180", title: "Tub Wall Set 5pc — Left Drain", marketplace: "Amazon", status: "in_progress", ownerId: "u_ap", notes: "A+ module pending", verifiedAt: null },
  { id: "a_4", projectId: "p_silicone", externalRef: "B08SW-TUB-1181", title: "Tub Wall Set 5pc — Right Drain", marketplace: "Amazon", status: "in_progress", ownerId: "u_ap", notes: null, verifiedAt: null },
  { id: "a_5", projectId: "p_silicone", externalRef: "B09SW-DOOR-7720", title: "Frameless Shower Door 34in", marketplace: "Amazon", status: "verified", ownerId: "u_jl", notes: null, verifiedAt: "2026-06-19T11:00:00Z" },
  { id: "a_6", projectId: "p_silicone", externalRef: "WMT-SUR-44120", title: "Sterling 60in Surround — White", marketplace: "Walmart", status: "verified", ownerId: "u_dt", notes: "Spec PDF updated", verifiedAt: "2026-06-21T10:00:00Z" },
  { id: "a_7", projectId: "p_silicone", externalRef: "WMT-SUR-44121", title: "Sterling 60in Surround — Sandbar", marketplace: "Walmart", status: "in_progress", ownerId: "u_dt", notes: "Spec PDF in edit", verifiedAt: null },
  { id: "a_8", projectId: "p_silicone", externalRef: "WMT-TUB-44990", title: "Sterling Tub Wall 4pc", marketplace: "Walmart", status: "pending", ownerId: "u_dt", notes: null, verifiedAt: null },
  { id: "a_9", projectId: "p_silicone", externalRef: "WAY-IMG-8810", title: "Glacier Bay Surround — Lifestyle Set", marketplace: "Wayfair", status: "flagged", ownerId: "u_sk", notes: "Old caulk tube visible in pkg shot", verifiedAt: null },
  { id: "a_10", projectId: "p_silicone", externalRef: "WAY-IMG-8811", title: "Glacier Bay Surround — Spec Render", marketplace: "Wayfair", status: "flagged", ownerId: "u_sk", notes: "Needs re-shoot", verifiedAt: null },
  { id: "a_11", projectId: "p_silicone", externalRef: "WAY-DOOR-2204", title: "Pivot Shower Door 32in — Brushed Nickel", marketplace: "Wayfair", status: "verified", ownerId: "u_mr", notes: null, verifiedAt: "2026-06-18T09:30:00Z" },
  { id: "a_12", projectId: "p_silicone", externalRef: "WAY-DOOR-2205", title: "Pivot Shower Door 36in — Chrome", marketplace: "Wayfair", status: "pending", ownerId: null, notes: null, verifiedAt: null },
  { id: "a_13", projectId: "p_silicone", externalRef: "B07SW-SUR-3250", title: "60×32 Alcove Surround — Bone", marketplace: "Amazon", status: "verified", ownerId: "u_jl", notes: null, verifiedAt: "2026-06-20T16:10:00Z" },
  { id: "a_14", projectId: "p_silicone", externalRef: "WMT-DOOR-51020", title: "Sterling Sliding Door 60in", marketplace: "Walmart", status: "verified", ownerId: "u_dt", notes: null, verifiedAt: "2026-06-21T10:20:00Z" },
  { id: "a_15", projectId: "p_silicone", externalRef: "B08SW-ACC-9001", title: "Caulk-Free Corner Shelf Kit", marketplace: "Amazon", status: "na", ownerId: "u_ap", notes: "No silicone reference — N/A", verifiedAt: null },
  { id: "a_16", projectId: "p_silicone", externalRef: "WAY-SUR-6601", title: "Ova Surround 48in — Carrara", marketplace: "Wayfair", status: "in_progress", ownerId: "u_mr", notes: null, verifiedAt: null },
];

// Full universe = 412 listings. The sample above represents the table; these
// buckets carry the real totals that drive the coverage meter.
export const AUDIT_BUCKETS: AuditBucket[] = [
  { marketplace: "Amazon", total: 196, verified: 188, inProgress: 5, pending: 2, flagged: 1 },
  { marketplace: "Walmart", total: 124, verified: 118, inProgress: 3, pending: 3, flagged: 0 },
  { marketplace: "Wayfair", total: 92, verified: 82, inProgress: 4, pending: 2, flagged: 4 },
];

export const AUDIT_TOTALS = AUDIT_BUCKETS.reduce(
  (a, b) => ({
    total: a.total + b.total,
    verified: a.verified + b.verified,
    inProgress: a.inProgress + b.inProgress,
    pending: a.pending + b.pending,
    flagged: a.flagged + b.flagged,
  }),
  { total: 0, verified: 0, inProgress: 0, pending: 0, flagged: 0 },
);

// ── Dashboard support: 14-day throughput (tasks verified per day) ─────────────
export const THROUGHPUT_14D: { day: string; verified: number; created: number }[] = [
  { day: "06/14", verified: 3, created: 4 },
  { day: "06/15", verified: 5, created: 3 },
  { day: "06/16", verified: 4, created: 6 },
  { day: "06/17", verified: 6, created: 2 },
  { day: "06/18", verified: 7, created: 5 },
  { day: "06/19", verified: 5, created: 4 },
  { day: "06/20", verified: 9, created: 3 },
  { day: "06/21", verified: 4, created: 7 },
  { day: "06/22", verified: 6, created: 8 },
  { day: "06/23", verified: 8, created: 5 },
  { day: "06/24", verified: 7, created: 4 },
  { day: "06/25", verified: 10, created: 6 },
  { day: "06/26", verified: 8, created: 3 },
  { day: "06/27", verified: 5, created: 2 },
];

// Recent activity feed for the dashboard (cross-project).
export const RECENT_ACTIVITY: { id: string; actorId: string; text: string; projectId: string; createdAt: string }[] = [
  { id: "f1", actorId: "u_ap", text: "commented on “Build 22 listings from content kit”", projectId: "p_walmart", createdAt: "2026-06-26T20:00:00Z" },
  { id: "f2", actorId: "u_cb", text: "flagged 7 below-cost SKUs in “Model margin floors”", projectId: "p_pricing", createdAt: "2026-06-26T17:30:00Z" },
  { id: "f3", actorId: "u_jl", text: "verified “Amazon bullet points — silicone language removed”", projectId: "p_silicone", createdAt: "2026-06-26T16:20:00Z" },
  { id: "f4", actorId: "u_mr", text: "marked “Resolve Amazon Prop 65 warning flags” blocked", projectId: "p_compliance", createdAt: "2026-06-26T15:00:00Z" },
  { id: "f5", actorId: "u_sk", text: "marked “Re-shoot hero images” blocked", projectId: "p_photo", createdAt: "2026-06-25T13:00:00Z" },
  { id: "f6", actorId: "u_dt", text: "moved “Walmart spec sheets” to In progress", projectId: "p_silicone", createdAt: "2026-06-25T17:40:00Z" },
];
